apiVersion: v1
kind: Service
metadata:
  name: kotsadm-dlv
  labels:
    app: kotsadm
    debug: "true"
spec:
  type: ClusterIP
  ports:
  - name: dlv
    port: 40000
    targetPort: dlv
  selector:
    app: kotsadm
